### ISSUE TITLE
Reloading changed files

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#36]
10x has always been a bit slow to reload files that have been modified externally. I'm not sure how it works but it only seems to check for file modification in certain circumstances like alt-tabbing. (unlike say, VSCode which reloads immediately on an external change).
Today I almost lost severals hours work because 10x failed to reload an externally modified file. I modified and saved it in 10x before noticing it was not the latest. The odd thing was that I had been alt-tabbing in and out dozens of times in the hours since the modification was made.
Luckily I recovered it from a continuous backup, but it is now going to worry me every time I go between editors!

**Comment by slynch8** [comment]
Sorry to hear that you almost lost work, I'm taking a look at this now. So far I haven't been able to reproduce this, there must be some case where it doesn't check for some reason.

**Comment by slynch8** [comment]
I found a potential bug in the file monitoring code, it was case sensitive, so if a file was opened with a different case it would miss it. However, I still couldn't reproduce the bug, 10x generally checks the case everywhere, but there could be some case I've missed. I've uploaded a fix for this (0.21.37.0), but I'll keep trying to find a repro. Let me know if it happens again.

**Comment by slynch8** [comment]
I've found a repro. Opening a file using goto-build-error would open the file with the wrong case and cause this problem. Anyway, I've changed it now so that case doesn't matter now so I'm confident this is fixed.

**Comment by Muzza** [comment]
I've noticed that the reloads are very hit and miss recently. 
When a file has been modified externally, it sometimes won't reload it. It seems to be either very delayed, or possibly related to alt-tabbing before it does the reload. (Although alt-tabbing does not reliably make it happen).
The search functionality also shows the old content until after a reload happens.

**Comment by slynch8** [comment]
I'm struggling to repro this. I wonder if 10x is busy parsing or something and the update thread is taking a long time to run. Would be interesting to see if 10x is busy when this happens. When 10x is idle CPU should be at 0.

**Comment by slynch8** [comment]
think I've found it, you're right, it was due to tabbing away while it was checking the files. Working on a fix.

**Comment by slynch8** [comment]
fixed (0.25.4)

**Comment by Muzza** [comment]
There are still problems with the reloading of externally changed files.
I just spent a minute editing a file, before 10x popped up a box saying it had been externally modified and did I want to discard the edits. The file had been externally modified by perforce (by a grab latest) about 5 minutes earlier. So this was a big delay.
Also, reloads still don't reliably occur unless I alt-tab in and out. My build process or python scripts often modifies files, and more often than not, they don't get reloaded by 10x unless I alt-tab twice.

**Comment by slynch8** [comment]
Are you calling CheckForModifiedFiles() from your build python script?

**Comment by slynch8** [comment]
In the latest version I've added some logging so that you can see what its doing. I'm wondering if it is just taking a really long time for some reason.
I also added these two commands:
- added ListFileStatusMonitorFiles to list the status of all monitored files
- added ListWorkspaceFiles to list all files in the current workspace

If you spot it happening again can you check the log please, and try running ListFileStatusMonitorFiles to check that it is monitoring the file.

**Comment by Muzza** [comment]
> 
> 
> Are you calling CheckForModifiedFiles() from your build python script?

When it is a script change, yes. But files are also modified by the MS Build process, which isn't using a script.
And sometimes I have an external program (not ran through a python script) that does some work, then outputs a file that I like to view in 10x alongside my main code. I end up alt-tabbing over and over just to check it is done and be sure 10x catches the change. I really feel it needs to monitor for changed files and reload it immediately, like VSCode does.

**Comment by Muzza** [comment]
FYI I've been using [this code on windows](https://github.com/jimbeveridge/readdirectorychanges) for many years.
With a few modifications I found it to be completely reliable for watching files/folders on Windows. Some file watcher implementations I'd tried previously were less than reliable.

**Comment by Muzza** [comment]
Running 'ListFileStatusMonitorFiles' I'm a bit surprised by its output. It lists every file in my solution, and even files from other workspaces I don't have open. I had assumed it would only monitor files currently open in an editor window.

**Comment by slynch8** [comment]
It monitors all files because the workspace search and the parser both need to know when any file in the workspace changes. 

Thanks for the link, I've been avoiding using directory watchers because workspaces can have hundreds of folders that would need watching and because it's not cross platform. But, I could use a watcher just for open files.

**Comment by slynch8** [comment]
hopefully fixed (0.25.18).

It now watches for changes on open files and updates them instantly. I also found a bug where if you closed a file, modified it and the reopened the file it would open the old file.

**Comment by Muzza** [comment]
> 
> 
> It monitors all files because the workspace search and the parser both need to know when any file in the workspace changes.
> 
> Thanks for the link, I've been avoiding using directory watchers because workspaces can have hundreds of folders that would need watching and because it's not cross platform. But, I could use a watcher just for open files.

In my programs I monitor a root folder with 2400 folders and 61000 files. I've not had any performance problems, and I can't imagine it being slower than monitoring individual files.

For cross platform I've used the [implementation here](https://github.com/jameswynn/simplefilewatcher)
Although I'm less sure of the reliability of this one. The windows implementation had problems that only showed up after long term usage, and I've not given the Linux/Mac implementations the same level of testing.

**Comment by slynch8** [comment]
The current solution is now using ReadDirectoryChangesW, but it's only watching directories of open files.

Good to know it can be done on Linux and OSX - thanks for the link.

The problem is that it would be very hard to tell the performance implications on general disk performance, I'm not even sure how you would profile this. I'm not sure how it is implemented at the OS level, and whether disk IO stalls on the callbacks. I'd hope it doesn't but who knows. You may be right though. I've kept my callbacks as light as possible, so maybe it's fine.

The other problem is deciding on the root folders to watch. Often project and sln files are not at the root folder, and some projects have multiple root folders. I do actually watch everything in my FastFind plugin and I have some code to decide on the root folders to watch so I might port it over at some point. Although I was never totally happy with it.

I will revisit this at some point, but hopefully the problems you were having are fixed now.

**Comment by Muzza** [comment]
I'm using this update today for the first time and I'm getting regular hangs when I do a build. 10x just freezes, as does MSBuild. I have to kill it.
My initial impression is that it does seem to be happening when my build process has updated a file, although it does not happen every time.

**Comment by slynch8** [comment]
That's strange, I can't think what would cause that. Next time it happens could you force a dump from TaskManager?

**Comment by slynch8** [comment]
think I've fixed it in (0.25.21)

**Comment by Muzza** [comment]
This all appears to be working nicely now.
