### ISSUE TITLE
Goto Definition fails for some symbols

### ISSUE THREAD

**Issue by nem0** [slynch8/10x#44]
Steps to reproduce:
1. download https://github.com/nem0/LumixEngine (small, 60MB repo)
2. run `projects/main.bat`, choose create project
3. open solution `projects/tmp/vs2019/LumixEngine.sln` in 10x
4. open file `pipeline.cpp`
5. find `PROFILE_FUNCTION` in `pipeline.cpp`
6. press Alt-G - `Goto Definition`
7. observe nothing happens

Note: it does not work for many symbols (macros, templates, simple functions)
Note: it does work for some symbols
Note: Alt-Shift-S `Find Symbol...` does mention the symbol as first option

**Comment by slynch8** [comment]
There is no preprocessor yet, so macros won't be resolved, but goto-def on macros should work... looks like it's because the macro is defined inside a namespace, I'll get that fixed.

Thanks, I'll take a look at LumixEngine. Apart from the preprocessor and stl most things should be parsing now.

**Comment by nem0** [comment]
It does not work for `profiler::pushInt` either, which is a simple function in namespace. Also `lua_*` functions are not found, or `lua_State`, which is just `struct`.

Another one is `minimum` in `math.h`, alt-g on `minimum(a.x, b.x),` finds incorrect overload (one with single argument)

**Comment by nem0** [comment]
Further investigation: some `lua_*` stuff are actually macros (e.g. `lua_pop`), and those work fine. Other  like `lua_getfield` are functions (from the same file) and do not work. 

I tried from scratch (new project and workspace) and  `lua_State` struct works now. Other issue are still present though.

**Comment by slynch8** [comment]
I found that multi-line macros were causing some of the functions in that file to fail
```
void Function()
{
    #define MY_MACRO() while { \
        somecode \
    }
    ...
```
It wasn't skipping multi-line macros properly, so it thought that the current function scope was closed with the end }

This is fixed in (0.22.26). There are probably still more issues, I'll take another look when I have time, but this should help.

**Comment by nem0** [comment]
Further investigation: I found out the problem with `lua_State` (and actually with lua macros too). When opening the solution for the very **first time** and going directly to `pipeline.cpp`, `Goto Definition` does not work on `lua_State` or lua macros. But after I open `lua.h` in 10x, `Goto Definition` starts working for `lua_State` and lua macros (e.g. `lua_pop`). It still does not know lua functions (e.g. `lua_getfield`) at all.

Note: `lua.h` is indirectly included in `pipeline.cpp`, but `lua.h` is not in VS project, while `pipeline.cpp` is.

**Comment by slynch8** [comment]
At the moment 10x only parses things in the VS project (it doesn't resolve includes yet). You can add addition include paths in the sln 'Local Settings' (right click the sln node in the tree)
